@startuml
title 库存管理系统类图

  interface Entity{
    + void init()
    + boolean validate()
    + entity find(id)
    + boolean checkIntegrity()
    + void put()
    + void putToDatastore()
  }
  interface Entitys{
    + void init()
    + boolean validateAll()
    + entity[] findAll()
    + boolean checkIntegrityAll()
    + void putAll()
    + void putToDatastore()
  }
  interface Repository{
    + init()
    + getValues()
    + setValues()
    + valuesToDtos()
    + dtosToValues()
  }

class MainController

package application{
  class PaymentSettlementFacade
}
package dataAccess{
  class ProductRepository
  class ProductInStockJapanRepository
  class ProductInStockChinaRepository
  class ProductSoldRepository
  class PaymentSettlementRepository
}
package service{
  package entity{
    class ProductEntity
    class ProductsEntity
    class ProductInStockJapanEntity
    class ProductsInStockJapanEntity
    class ProductInStockChinaEntity
    class ProductsInStockChinaEntity
    class ProductSoldEntity
    class ProductsSoldEntity
    class PaymentSettlementEntity
    class PaymentSettlementsEntity
  }

}

ProductEntity -.up|> Entity
ProductInStockJapanEntity -.up|> Entity
ProductInStockChinaEntity -.up|> Entity
ProductSoldEntity -.up|> Entity
PaymentSettlementEntity -.up|> Entity

ProductsEntity -.up|> Entitys
ProductsInStockJapanEntity -.up|> Entitys
ProductsInStockChinaEntity -.up|> Entitys
ProductsSoldEntity -.up|> Entitys
PaymentSettlementsEntity -.up|> Entitys

ProductsEntity o-- ProductEntity
ProductsInStockJapanEntity o-- ProductInStockJapanEntity
ProductsInStockChinaEntity o-- ProductInStockChinaEntity
ProductsSoldEntity o-- ProductSoldEntity
PaymentSettlementsEntity o-- PaymentSettlementEntity

ProductRepository -.|> Repository
ProductInStockJapanRepository -.|> Repository
ProductInStockChinaRepository -.|> Repository
ProductSoldRepository -.|> Repository
PaymentSettlementRepository -.|> Repository

MainController -.> PaymentSettlementFacade : use
PaymentSettlementFacade -.> PaymentSettlementEntity : use
PaymentSettlementEntity -.> PaymentSettlementRepository : use
PaymentSettlementEntity -.> ProductEntity : use
ProductEntity -.> ProductRepository : use
ProductInStockJapanEntity -.> ProductInStockJapanRepository : use
ProductInStockJapanEntity -.> ProductEntity : use
ProductInStockChinaEntity -.> ProductInStockChinaRepository : use
ProductInStockChinaEntity -.> ProductEntity : use
ProductSoldEntity -.> ProductSoldRepository : use
ProductSoldEntity -.> ProductEntity : use





@enduml
