@startuml
left to right direction
title 库存管理系统robustness图

actor 进货人
actor 出货人

boundary 商品记录信息操作画面
'ote left of 商品记录信息操作画面 : 该画面可进行商品登录，商品状态查询，商品更新

boundary 货款结算画面
boundary 货款结算一览画面

control 商品记录信息登录
control 商品记录信息更新
control 商品记录信息查询
control 商品记录信息删除
control 货款结算
control 货款结算查询
control 货款结算取消

entity 商品记录信息
entity 货款结算记录信息

'relationship
进货人 --> 商品记录信息操作画面
出货人 --> 商品记录信息操作画面
商品记录信息操作画面 --> 商品记录信息登录
商品记录信息操作画面 --> 商品记录信息更新
商品记录信息操作画面 --> 商品记录信息查询
商品记录信息操作画面 --> 商品记录信息删除

商品记录信息登录 -- 商品记录信息
商品记录信息更新 -- 商品记录信息
商品记录信息查询 -- 商品记录信息
商品记录信息删除 -- 商品记录信息

进货人 --> 货款结算画面
出货人 --> 货款结算画面
进货人 --> 货款结算一览画面
出货人 --> 货款结算一览画面

货款结算画面 --> 货款结算
货款结算一览画面 --> 货款结算查询
货款结算一览画面 --> 货款结算取消

货款结算 -- 货款结算记录信息
货款结算查询 -- 货款结算记录信息
货款结算取消 -- 货款结算记录信息
@enduml
