@startuml
title 货款结算activity图
start
:从已售出商品一览中读取全部信息;
while(还有未处理商品?)
  if(商品的结算月 == 空 && 商品的最新更新日期的月 == 结算处理的月 && 商品已确认支付) then (yes)
    :将(商品数量 x 商品进货价)加入总成本;
    :将(商品数量 x 商品销售价)加入总销售额;
  else(no)
  endif
endwhile
:将总成本变换为人民币;
:以人民币计算总利润;
:将总销售额和总利润变换为日元;
:将计算的结果保存到[货款结算一览];
stop
@enduml
